# Generated by Django 5.2.18 on 2026-10-07 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='meaningful_work',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='visibility',
            field=models.CharField(choices=[('approved_recruiters', 'Visible to approved recruiters'), ('matching_roles', 'Only matching roles'), ('not_looking', 'Not looking right now')], default='approved_recruiters', max_length=30),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='work_preferences',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
