# Generated by Django 5.2.18 on 2026-10-07 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0002_candidateprofile_meaningful_work_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='visibility',
            field=models.CharField(blank=True, choices=[('approved_recruiters', 'Visible to approved recruiters'), ('matching_roles', 'Only matching roles'), ('not_looking', 'Not looking right now')], default='', max_length=30),
        ),
    ]
