# Generated by Django 5.2.18 on 2026-10-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0003_alter_candidateprofile_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='profile_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
