# Generated by Django 5.2.18 on 2026-10-07 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def require_new_consent_without_disrupting_existing_login(apps, schema_editor):
    candidate_profile = apps.get_model("talent", "CandidateProfile")
    candidate_profile.objects.filter(email_verified_at__isnull=True).update(
        email_verified_at=timezone.now()
    )
    candidate_profile.objects.filter(profile_status="submitted").update(
        profile_status="draft", submitted_at=None
    )


class Migration(migrations.Migration):

    dependencies = [
        ("talent", "0004_candidateprofile_profile_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='submission_consent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='submission_consent_version',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.RunPython(
            require_new_consent_without_disrupting_existing_login,
            migrations.RunPython.noop,
        ),
        migrations.CreateModel(
            name='AccountActionToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('verify_email', 'Verify email'), ('reset_password', 'Reset password')], max_length=30)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_action_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'purpose', 'created_at'], name='talent_acco_user_id_cf66f0_idx')],
            },
        ),
    ]
