# Generated by Django 5.2.18 on 2026-10-07 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0005_candidateprofile_email_verified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateupdatenotification',
            name='change_type',
            field=models.CharField(choices=[('resume', 'Resume'), ('profile', 'Profile')], default='resume', max_length=20),
        ),
        migrations.AlterField(
            model_name='candidateupdatenotification',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='talent.resume'),
        ),
        migrations.CreateModel(
            name='ProjectCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to='talent.candidateprofile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='talent.project')),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='candidates',
            field=models.ManyToManyField(blank=True, related_name='recruiter_projects', through='talent.ProjectCandidate', to='talent.candidateprofile'),
        ),
        migrations.AddConstraint(
            model_name='projectcandidate',
            constraint=models.UniqueConstraint(fields=('project', 'candidate'), name='unique_project_candidate'),
        ),
    ]
