# Generated by Django 5.2.18 on 2026-10-07 12:43

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


def mark_existing_resumes_completed(apps, schema_editor):
    Resume = apps.get_model("talent", "Resume")
    ResumeProcessingJob = apps.get_model("talent", "ResumeProcessingJob")
    now = django.utils.timezone.now()
    Resume.objects.update(
        processing_status="completed",
        scan_status="clean",
        processing_error="",
    )
    ResumeProcessingJob.objects.bulk_create(
        [
            ResumeProcessingJob(
                resume_id=resume_id,
                state="completed",
                attempts=1,
                max_attempts=3,
                available_at=now,
                completed_at=now,
                enqueued_at=now,
            )
            for resume_id in Resume.objects.values_list("id", flat=True)
        ]
    )


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0008_workexperience_gap_reason_and_recruiting_stages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimitBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('window_started_at', models.DateTimeField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeProcessingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('enqueued_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('queue_message_id', models.CharField(blank=True, max_length=180)),
                ('last_error', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='resume',
            name='processing_error',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='resume',
            name='processing_status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', max_length=20),
        ),
        migrations.AddField(
            model_name='resume',
            name='processing_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='scan_status',
            field=models.CharField(choices=[('quarantined', 'Quarantined'), ('scanning', 'Scanning'), ('clean', 'Clean'), ('infected', 'Infected'), ('failed', 'Scan failed')], default='quarantined', max_length=20),
        ),
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(upload_to='quarantine/%Y/%m/'),
        ),
        migrations.AddIndex(
            model_name='candidateprofile',
            index=models.Index(fields=['profile_status', 'visibility'], name='talent_cand_profile_90833c_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateprofile',
            index=models.Index(fields=['headline'], name='talent_cand_headlin_e2bce4_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateprofile',
            index=models.Index(fields=['location'], name='talent_cand_locatio_976e36_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateprofile',
            index=models.Index(fields=['total_experience'], name='talent_cand_total_e_275909_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateprofile',
            index=models.Index(fields=['notice_period_days'], name='talent_cand_notice__e5d6fd_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateprofile',
            index=models.Index(fields=['expected_salary_lpa'], name='talent_cand_expecte_f15e49_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateprofile',
            index=models.Index(fields=['employment_type'], name='talent_cand_employm_8d594e_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateprofile',
            index=django.contrib.postgres.indexes.GinIndex(fields=['skills'], name='candidate_skills_gin'),
        ),
        migrations.AddIndex(
            model_name='candidateprofile',
            index=django.contrib.postgres.indexes.GinIndex(fields=['work_preferences'], name='candidate_workprefs_gin'),
        ),
        migrations.AddIndex(
            model_name='ratelimitbucket',
            index=models.Index(fields=['updated_at'], name='talent_rate_updated_68dab4_idx'),
        ),
        migrations.AddField(
            model_name='resumeprocessingjob',
            name='resume',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processing_job', to='talent.resume'),
        ),
        migrations.RunPython(mark_existing_resumes_completed, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='resumeprocessingjob',
            index=models.Index(fields=['state', 'available_at'], name='talent_resu_state_f7470b_idx'),
        ),
    ]
