# Generated by Django 5.2.18 on 2026-10-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0009_ratelimitbucket_resumeprocessingjob_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='candidatestatus',
            index=models.Index(fields=['recruiter', 'status'], name='talent_cand_recruit_da40b5_idx'),
        ),
        migrations.AddIndex(
            model_name='profileview',
            index=models.Index(fields=['recruiter', 'viewed_at'], name='talent_prof_recruit_db3799_idx'),
        ),
    ]
