import { expect, test, type Page, type TestInfo } from '@playwright/test'
import { issueLocalAccountToken } from './account-token'

async function screenshot(page: Page, info: TestInfo, name: string, width: number) {
  await page.evaluate(() => document.fonts.ready)
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(width)
  await page.screenshot({ path: info.outputPath(`${name}-${width}.png`), fullPage: true, animations: 'disabled' })
}

for (const width of [1440, 1024, 390]) {
  test(`authentication screens remain clear and usable at ${width}px`, async ({ page }, info) => {
    await page.setViewportSize({ width, height: 900 })
    await page.goto('/')
    for (const role of ['recruiters', 'candidates']) {
      await page.getByTestId(`for-${role}`).click()
      await expect(page.getByRole('heading', { name: 'Create your account' })).toBeVisible()
      await expect(page.getByLabel('Full name')).toBeVisible()
      await expect(page.getByText(role === 'recruiters' ? 'RECRUITER WORKSPACE' : 'CANDIDATE PROFILE', { exact: true })).toBeVisible()
      await page.getByLabel('Email').focus()
      await expect(page.getByLabel('Email')).toHaveCSS('border-color', 'rgb(109, 74, 255)')
      await screenshot(page, info, `${role}-signup`, width)
      await page.getByRole('button', { name: /Already have an account/ }).click()
      await expect(page.getByRole('heading', { name: 'Welcome back' })).toBeVisible()
      await expect(page.getByLabel('Full name')).toHaveCount(0)
      await screenshot(page, info, `${role}-login`, width)
      await page.getByRole('button', { name: 'Forgot password?' }).click()
      await expect(page.getByRole('heading', { name: 'Forgot your password?' })).toBeVisible()
      await expect(page.getByLabel('Password', { exact: true })).toHaveCount(0)
      await screenshot(page, info, `${role}-forgot`, width)
      await page.getByRole('button', { name: 'Back to login' }).click()
      await expect(page.getByRole('heading', { name: 'Welcome back' })).toBeVisible()
      await page.getByRole('button', { name: '← Back to Enter' }).click()
    }
    await page.goto('/?reset-password=invalid-ui-test-token')
    await expect(page.getByRole('heading', { name: 'Choose a new password' })).toBeVisible()
    await page.getByLabel('New password').fill('sample-password-123')
    await page.getByLabel('Confirm password').fill('different-password-123')
    await page.getByRole('button', { name: 'Reset password', exact: true }).click()
    await expect(page.getByRole('alert')).toHaveText('Passwords do not match.')
    await screenshot(page, info, 'reset-password', width)
    await page.goto('/?verify-email=invalid-ui-test-token')
    await expect(page.getByRole('heading', { name: 'Verification link unavailable' })).toBeVisible()
    await expect(page.getByRole('alert')).toBeVisible()
    await screenshot(page, info, 'verification-error', width)
    await page.getByRole('link', { name: 'Return to Enter', exact: true }).click()
    await expect(page.getByTestId('for-candidates')).toBeVisible()
  })
}

test('candidate verification, resend, login and password reset use the existing real APIs', async ({ page }, info) => {
  test.setTimeout(60_000)
  await page.setViewportSize({ width: 390, height: 844 })
  const email = `auth-ui-candidate-${Date.now()}@example.com`
  const password = 'Auth-ui-original-123!'
  await page.goto('/')
  await page.getByTestId('for-candidates').click()
  await page.getByLabel('Full name').fill('Maya Rao')
  await page.getByLabel('Email').fill(email)
  await page.getByLabel('Password', { exact: true }).fill(password)
  await page.getByRole('button', { name: 'Create account' }).click()
  await expect(page.getByRole('heading', { name: 'Check your email' })).toBeVisible({ timeout: 15_000 })
  await expect(page.getByText(email, { exact: true })).toBeVisible()
  await screenshot(page, info, 'verification-pending', 390)
  const resend = page.waitForResponse(response => response.url().includes('/auth/resend-verification/') && response.request().method() === 'POST')
  await page.getByRole('button', { name: 'Resend verification email' }).click()
  expect((await resend).ok()).toBeTruthy()
  await page.goto(`/?verify-email=${issueLocalAccountToken(email, 'verify_email')}`)
  await expect(page.getByRole('heading', { name: 'Drop your resume' })).toBeVisible()
  await page.getByRole('button', { name: 'Log out' }).click()
  await page.getByTestId('for-candidates').click()
  await page.getByRole('button', { name: /Already have an account/ }).click()
  await page.getByLabel('Email').fill(email)
  await page.getByLabel('Password', { exact: true }).fill(password)
  await page.getByRole('button', { name: 'Log in', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Drop your resume' })).toBeVisible()
  await page.getByRole('button', { name: 'Log out' }).click()
  await page.getByTestId('for-candidates').click()
  await page.getByRole('button', { name: /Already have an account/ }).click()
  await page.getByRole('button', { name: 'Forgot password?' }).click()
  await page.getByLabel('Email').fill(email)
  await page.getByRole('button', { name: 'Send reset link' }).click()
  await expect(page.getByRole('status')).toContainText('If an account exists')
  await screenshot(page, info, 'forgot-success', 390)
  await page.goto(`/?reset-password=${issueLocalAccountToken(email, 'reset_password')}`)
  await page.getByLabel('New password').fill('Auth-ui-updated-456!')
  await page.getByLabel('Confirm password').fill('Auth-ui-updated-456!')
  await page.getByRole('button', { name: 'Reset password', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Password updated' })).toBeVisible()
  await screenshot(page, info, 'reset-success', 390)
  await page.getByRole('button', { name: 'Continue to login' }).click()
  await expect(page.getByRole('heading', { name: 'Welcome back' })).toBeVisible()
  await page.getByLabel('Email').fill(email)
  await page.getByLabel('Password', { exact: true }).fill('Auth-ui-updated-456!')
  await page.getByRole('button', { name: 'Log in', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Drop your resume' })).toBeVisible()
})

test('recruiter signup and login keep their existing workspace destination', async ({ page }) => {
  const email = `auth-ui-recruiter-${Date.now()}@example.com`
  await page.goto('/')
  await page.getByTestId('for-recruiters').click()
  await page.getByLabel('Full name').fill('Robin Shah')
  await page.getByLabel('Company').fill('Auth UI Test Company')
  await page.getByLabel('Email').fill(email)
  await page.getByLabel('Password', { exact: true }).fill('Auth-ui-recruiter-123!')
  await page.getByRole('button', { name: 'Create account' }).click()
  await expect(page.getByRole('heading', { name: 'Who are we hiring today?' })).toBeVisible()
  await page.getByRole('button', { name: 'Log out' }).click()
  await page.locator('.ce-login summary').click()
  await page.getByRole('button', { name: 'Recruiter log in', exact: true }).click()
  await page.getByLabel('Email').fill(email)
  await page.getByLabel('Password', { exact: true }).fill('Incorrect-password-123!')
  await page.getByRole('button', { name: 'Log in', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Invalid email or password.')
  await page.getByLabel('Password', { exact: true }).fill('Auth-ui-recruiter-123!')
  await page.getByRole('button', { name: 'Log in', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Who are we hiring today?' })).toBeVisible()
})

test('auth respects reduced motion and maintains keyboard-visible focus', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/')
  await page.getByTestId('for-candidates').click()
  await expect(page.locator('.auth-card')).toHaveCSS('animation-name', 'none')
  await page.getByLabel('Full name').focus()
  await page.keyboard.press('Tab')
  await expect(page.getByLabel('Email')).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(page.getByLabel('Password', { exact: true })).toBeFocused()
  await page.keyboard.press('Tab')
  const create = page.getByRole('button', { name: 'Create account' })
  await expect(create).toBeFocused()
  await expect(create).toHaveCSS('outline-style', 'solid')
})
