import { expect, test } from '@playwright/test'
import path from 'node:path'
import { issueLocalAccountToken } from './account-token'

test('candidate completes a conversational resume profile and preferences persist', async ({ page }) => {
  const unique = Date.now()
  const email = `candidate-${unique}@example.com`
  const meaningfulWork = 'I led a payments recovery platform that reduced incident recovery time by 60%.'

  await page.goto('/')
  await page.getByTestId('for-candidates').click()
  await page.getByLabel('Full name').fill('Asha Rao')
  await page.getByLabel('Email').fill(email)
  await page.getByLabel('Password').fill('strong-pass-123')
  await page.getByRole('button', { name: 'Create account' }).click()
  await expect(page.getByRole('heading', { name: 'Check your email' })).toBeVisible({ timeout: 15_000 })
  await expect(page.getByRole('link', { name: 'Verify this local account' })).toBeVisible()
  const verificationToken = issueLocalAccountToken(email, 'verify_email')
  await page.goto(`/?verify-email=${verificationToken}`)
  await expect(page.getByRole('heading', { name: 'Drop your resume' })).toBeVisible()
  expect(await page.evaluate(() => document.cookie)).not.toContain('enter_session')
  await expect(page.getByText('CANDIDATE PLATFORM')).toHaveCount(0)
  await expect(page.locator('.profile-board')).toHaveCount(0)
  await expect(page.getByText('Only missing details are shown for confirmation')).toBeVisible()

  const fixture = path.resolve('../backend/tests/fixtures/asha-rao-resume.docx')
  await page.getByTestId('resume-input').setInputFiles(fixture)
  await expect(page.getByText("We've built your starting profile", { exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: /Build a profile that/ })).toBeVisible()
  await expect(page.getByText('Your resume gave us a great start.')).toBeVisible()
  await expect(page.getByText('We need 3 more details to complete your profile.')).toBeVisible()
  await expect(page.locator('.experience-card').getByText('Senior Backend Engineer')).toBeVisible()

  await page.getByRole('button', { name: /Complete my profile/ }).click()
  await expect(page.getByRole('heading', { name: /what kind of work setup works for you/i })).toBeVisible()
  const quickStep = page.locator('.quick-step')
  await quickStep.getByRole('button', { name: 'Remote', exact: true }).click()
  await quickStep.getByRole('button', { name: /Save and continue/ }).click()
  await expect(page.getByRole('heading', { name: /How should recruiters find you/i })).toBeVisible()
  await quickStep.getByRole('button', { name: /Only matching roles/ }).click()
  await expect(quickStep.getByRole('heading', { name: /most meaningful thing/i })).toBeVisible()
  await quickStep.getByPlaceholder(/What did you build/).fill(meaningfulWork)
  await quickStep.getByRole('button', { name: /Save and continue/ }).click()
  await expect(page.getByText('Your profile is ready')).toBeVisible()

  const about = page.locator('.about-card')
  await about.getByRole('button', { name: /Edit/ }).click()
  await about.getByLabel('Current role').fill('Staff Backend Engineer')
  await about.getByRole('button', { name: 'Save', exact: true }).click()

  const experience = page.locator('.experience-card')
  await experience.getByRole('button', { name: 'Edit' }).click()
  await experience.getByLabel('Experience role 1').fill('Lead Backend Engineer')
  await experience.getByRole('button', { name: 'Save experience' }).click()

  const contact = page.locator('.contact-card')
  await contact.getByRole('button', { name: /Edit/ }).click()
  await expect(contact.getByLabel('LinkedIn')).toHaveValue('https://linkedin.com/in/asharao')
  await expect(contact.getByLabel('GitHub / portfolio')).toHaveValue('https://github.com/asharao')
  await contact.getByLabel('Expected compensation (LPA)').fill('30')
  await contact.getByRole('button', { name: 'Save', exact: true }).click()

  const preferences = page.locator('.preferences-card')
  await preferences.getByRole('button', { name: /Only matching roles/ }).click()
  await preferences.getByRole('button', { name: 'Hybrid', exact: true }).click()
  await expect(preferences.getByRole('button', { name: /Only matching roles/ })).toHaveClass(/selected/)
  await expect(preferences.getByRole('button', { name: 'Remote', exact: true })).toHaveClass(/selected/)
  await expect(preferences.getByRole('button', { name: 'Hybrid', exact: true })).toHaveClass(/selected/)

  await page.getByRole('button', { name: /Review & submit/ }).click()
  const review = page.locator('.review-submit')
  await expect(review.getByText('All required details are ready.')).toBeVisible()
  await review.getByLabel('Profile-sharing consent').check()
  await review.getByRole('button', { name: /Submit my profile/ }).click()
  await expect(page.getByRole('heading', { name: /You’re all set/ })).toBeVisible()

  await page.getByRole('button', { name: 'Log out' }).click()
  await page.getByTestId('for-candidates').click()
  await page.getByRole('button', { name: /Already have an account/ }).click()
  await page.getByRole('button', { name: 'Forgot password?' }).click()
  await page.getByLabel('Email').fill(email)
  await page.getByRole('button', { name: 'Send reset link' }).click()
  await expect(page.getByText(/If an account exists/)).toBeVisible()
  const resetToken = issueLocalAccountToken(email, 'reset_password')
  await page.goto(`/?reset-password=${resetToken}`)
  await page.getByLabel('New password').fill('new-strong-pass-456')
  await page.getByLabel('Confirm password').fill('new-strong-pass-456')
  await page.getByRole('button', { name: 'Reset password' }).click()
  await expect(page.getByRole('heading', { name: 'Password updated' })).toBeVisible()
  await page.getByRole('button', { name: 'Continue to login' }).click()
  await page.getByRole('button', { name: /Already have an account/ }).click()
  await page.getByLabel('Email').fill(email)
  await page.getByLabel('Password').fill('new-strong-pass-456')
  await page.getByRole('button', { name: 'Log in', exact: true }).click()

  await expect(page.getByText('Staff Backend Engineer')).toBeVisible()
  await expect(page.getByText(meaningfulWork)).toBeVisible()
  await expect(page.getByText('Lead Backend Engineer')).toBeVisible()
  await expect(page.getByText('Version 1')).toBeVisible()
  await expect(page.getByRole('heading', { name: /You’re all set/ })).toBeVisible()
  const persistedPreferences = page.locator('.preferences-card')
  await expect(persistedPreferences.getByRole('button', { name: /Only matching roles/ })).toHaveClass(/selected/)
  await expect(persistedPreferences.getByRole('button', { name: 'Remote', exact: true })).toHaveClass(/selected/)
  await expect(persistedPreferences.getByRole('button', { name: 'Hybrid', exact: true })).toHaveClass(/selected/)

  await persistedPreferences.getByRole('button', { name: /Not looking right now/ }).click()
  await expect(page.getByText(/recruiters won’t see it in search/)).toBeVisible()
  await page.getByTestId('resume-input').setInputFiles(fixture)
  await expect(page.getByText('Version 2')).toBeVisible()

  await page.getByRole('button', { name: /Delete my account/ }).click()
  const deletion = page.locator('.account-controls')
  await deletion.getByLabel('Current password').fill('new-strong-pass-456')
  await deletion.getByLabel('Type DELETE to confirm').fill('DELETE')
  await deletion.getByRole('button', { name: 'Permanently delete my account' }).click()
  await expect(page.getByRole('heading', { name: 'Your account has been deleted' })).toBeVisible()
})
